command:
  - python
  - src/app.py
env:
  - name: ENV
    value: production
  - name: DEBUG
    value: "false"
  - name: DATABRICKS_WAREHOUSE_ID
    value: a53b3ef899f7696a
  - name: DATABRICKS_CATALOG
    value: sandbox
  - name: DATABRICKS_SCHEMA
    value: menu_grading
