"""Compile a GradingReport into a FeedbackPreview and generate email HTML."""

from __future__ import annotations

import sys
import os
from typing import Optional, List, Dict

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

from src.config import settings


def compile_feedback(report: Dict) -> Dict:
    """Build a FeedbackPreview dict from a grading report."""
    sections = []
    section_scores = report.get("section_scores", {})
    for section_name, scores in section_scores.items():
        label = section_name.replace("_", " ").title()
        sections.append({
            "name": label,
            "score": scores.get("score", 0),
            "earned": scores.get("earned", 0),
            "max_points": scores.get("max_points", 0),
            "grade": _score_to_grade(scores.get("score", 0)),
        })

    top_issues = _extract_top_issues(report)
    recommendations = _generate_recommendations(report)

    return {
        "to_email": report["builder_email"],
        "to_name": report["builder_name"],
        "cc_email": settings.FEEDBACK_CC_EMAIL,
        "reply_to": report["graded_by"],
        "subject": "Menu Grading Feedback: %s" % report["merchant_name"],
        "sections": sections,
        "top_issues": top_issues,
        "recommendations": recommendations,
    }


def generate_email_html(preview: Dict, personal_notes: Optional[str] = None) -> str:
    """Render feedback preview into an HTML email body."""
    sections_html = ""
    for s in preview["sections"]:
        color = _grade_color(s["grade"])
        sections_html += (
            '<tr>'
            '<td style="padding:8px 12px;border-bottom:1px solid #eee;">%s</td>'
            '<td style="padding:8px 12px;border-bottom:1px solid #eee;text-align:center;">'
            '<span style="color:%s;font-weight:bold;">%.0f%%</span>'
            '</td>'
            '<td style="padding:8px 12px;border-bottom:1px solid #eee;text-align:center;">%.1f/%.0f</td>'
            '</tr>'
        ) % (s["name"], color, s["score"], s["earned"], s["max_points"])

    issues_html = ""
    for issue in preview["top_issues"]:
        severity_color = {"high": "#dc2626", "medium": "#f59e0b", "low": "#3b82f6"}.get(
            issue.get("severity", "medium"), "#6b7280"
        )
        issues_html += (
            '<li style="margin-bottom:8px;">'
            '<span style="color:%s;font-weight:bold;">[%s]</span> %s'
            '</li>'
        ) % (severity_color, issue.get("severity", "info").upper(), issue.get("description", ""))

    recs_html = "".join(
        "<li style='margin-bottom:6px;'>%s</li>" % r for r in preview["recommendations"]
    )

    notes_section = ""
    if personal_notes:
        notes_section = (
            '<div style="margin-top:24px;padding:16px;background:#f0fdf4;'
            'border-left:4px solid #22c55e;border-radius:4px;">'
            '<h3 style="margin:0 0 8px;">Personal Notes from Your Grader</h3>'
            '<p style="margin:0;">%s</p>'
            '</div>'
        ) % personal_notes

    return (
        '<div style="font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\','
        'Roboto,sans-serif;max-width:640px;margin:0 auto;padding:24px;">'
        '<div style="background:#1e40af;color:white;padding:24px;border-radius:8px 8px 0 0;">'
        '<h1 style="margin:0;font-size:20px;">Menu Build Quality Report</h1>'
        '<p style="margin:8px 0 0;opacity:0.9;">%s</p>'
        '</div>'
        '<div style="background:white;padding:24px;border:1px solid #e5e7eb;border-top:none;">'
        '<p>Hi %s,</p>'
        '<p>Here is the quality feedback for your recent menu build.</p>'
        '<h2 style="font-size:16px;margin-top:24px;">Section Scores</h2>'
        '<table style="width:100%%;border-collapse:collapse;">'
        '<thead><tr style="background:#f9fafb;">'
        '<th style="padding:8px 12px;text-align:left;">Section</th>'
        '<th style="padding:8px 12px;text-align:center;">Score</th>'
        '<th style="padding:8px 12px;text-align:center;">Points</th>'
        '</tr></thead>'
        '<tbody>%s</tbody></table>'
        '<h2 style="font-size:16px;margin-top:24px;">Top Issues</h2>'
        '<ul style="padding-left:20px;">%s</ul>'
        '<h2 style="font-size:16px;margin-top:24px;">Recommendations</h2>'
        '<ul style="padding-left:20px;">%s</ul>'
        '%s'
        '</div>'
        '<div style="background:#f9fafb;padding:16px 24px;border:1px solid #e5e7eb;'
        'border-top:none;border-radius:0 0 8px 8px;text-align:center;color:#6b7280;font-size:13px;">'
        '<p>This feedback was generated by the Menu Grading Tool. '
        'Reply to this email to reach your grader.</p>'
        '</div></div>'
    ) % (
        preview["subject"],
        preview["to_name"],
        sections_html,
        issues_html,
        recs_html,
        notes_section,
    )


def _score_to_grade(score: float) -> str:
    if score >= 90:
        return "A"
    if score >= 80:
        return "B"
    if score >= 70:
        return "C"
    if score >= 60:
        return "D"
    return "F"


def _grade_color(grade: str) -> str:
    return {
        "A": "#16a34a",
        "B": "#2563eb",
        "C": "#f59e0b",
        "D": "#ea580c",
        "F": "#dc2626",
    }.get(grade, "#6b7280")


def _extract_top_issues(report: Dict) -> List[Dict]:
    """Pull out the most impactful issues from the report."""
    top = []
    issues = report.get("issues", {})

    for disc in issues.get("price_discrepancies", []):
        top.append({
            "category": "Price",
            "severity": "high",
            "description": "Price discrepancy on '%s'" % disc.get("item", "Unknown"),
        })

    for err in issues.get("capitalization_errors", []):
        top.append({
            "category": "Neatness",
            "severity": "medium",
            "description": "Capitalization issue on '%s' — expected '%s'"
            % (err.get("item", "Unknown"), err.get("expected", "")),
        })

    for mod in issues.get("modifier_issues", []):
        top.append({
            "category": "Organization",
            "severity": "medium",
            "description": mod.get("detail", "Modifier issue on '%s'" % mod.get("item", "Unknown")),
        })

    for miss in issues.get("missing_items", []):
        top.append({
            "category": "Thoroughness",
            "severity": "high",
            "description": "Missing item: '%s' (found on %s)"
            % (miss.get("item", "Unknown"), miss.get("source", "source")),
        })

    for dup in issues.get("duplicates", []):
        items_str = ", ".join(dup.get("items", []))
        top.append({
            "category": "Organization",
            "severity": "low",
            "description": "Possible duplicates: %s" % items_str,
        })

    return sorted(top, key=lambda x: {"high": 0, "medium": 1, "low": 2}.get(x["severity"], 3))


def _generate_recommendations(report: Dict) -> List[str]:
    """Generate actionable recommendations based on report data."""
    recs = []
    section_scores = report.get("section_scores", {})

    neatness = section_scores.get("neatness", {}).get("score", 100)
    if neatness < 80:
        recs.append("Review title case rules — ensure all item names follow proper capitalization.")

    accuracy = section_scores.get("accuracy", {}).get("score", 100)
    if accuracy < 85:
        recs.append("Double-check prices against the source menu before finalizing the build.")

    org = section_scores.get("organization", {}).get("score", 100)
    if org < 80:
        recs.append("Ensure modifier groups are properly set up for items that need size/customization options.")

    thoroughness = section_scores.get("thoroughness", {}).get("score", 100)
    if thoroughness < 80:
        recs.append("Cross-reference all source menu items to make sure nothing is missing from the build.")

    issues = report.get("issues", {})
    if issues.get("duplicates"):
        recs.append("Check for duplicate items that may confuse merchants or customers.")

    if not recs:
        recs.append("Great job! Keep up the consistent quality across all build categories.")

    return recs
